### PR TITLE
Close channel used to collect credential information.

### PR DESCRIPTION
**Pull request by keep94**

### CODE REVIEW

**Comment by rgooch** [comment]
Why is this needed?

**Comment by keep94** [comment]
Code works fine the way it is, but closing the channel lets you use the channel in a for..range which makes for slightly cleaner code.

**Comment by keep94** [comment]
Anyway what brought be to look at this code was that I am thinking about how to make our CIS collector more resilient to permission problems.

**Comment by rgooch** [comment]
You could instead close the channel after the `for range accountNames` loop. That would avoid the need to use another synchronisation primitive.

**Comment by keep94** [comment]
Ok, I close the channel after the for loop per your suggestion.

**Pull request merged**
